import type { EnterpriseOffer, Experiment, Mission, NetworkNode, PersonMatch, PurposeProfile } from "./types";

export const starterPurpose: PurposeProfile = {
  intention: "Turn the work I care about into useful, testable projects with the right people and a path to sustainable income.",
  strengths: ["systems thinking", "building", "pattern recognition", "creative synthesis"],
  needs: ["implementation partners", "distribution", "repeatable launch path"],
  constraints: ["protect creator ownership", "keep the system understandable", "ship real outcomes"],
  interests: ["resonance mechanics", "human design", "creator tools", "citizen science"],
  currentVector: "Publish one working node, recruit one complementary collaborator, and collect one measurable outcome.",
  roadmap: [
    { title: "Make the work legible", detail: "Package one idea as a node with a clear outcome, need, and next action.", status: "now" },
    { title: "Find the missing role", detail: "Match by project need, strengths, context, and resonance rather than follower count.", status: "next" },
    { title: "Run the field test", detail: "Use a mission with evidence capture and a visible definition of done.", status: "next" },
    { title: "Launch or replicate", detail: "Route the validated work into Science, Enterprise, or both.", status: "later" },
  ],
};

export const starterNodes: NetworkNode[] = [
  {
    id: "node-gold-crucible",
    title: "Golden Crucible Field Study",
    summary: "A public, replicable experiment node for testing an unconventional field hypothesis with transparent methods and logs.",
    pathway: "science",
    status: "testing",
    tags: ["citizen science", "replication", "field log"],
    needs: ["replicators", "sensor design", "method review"],
    offers: ["open protocol", "shared data", "replication credit"],
    targetOutcome: "Three independent replications with comparable observations.",
    creator: "Celestial",
    collaborators: 4,
    replications: 2,
    support: 240,
    resonance: 88,
  },
  {
    id: "node-paper-launcher",
    title: "Paper Creator Launcher",
    summary: "A creator pipeline that turns project files into a presentable node, site, and launch package without requiring a full dev team.",
    pathway: "enterprise",
    status: "active",
    tags: ["creator tools", "IDE", "launch"],
    needs: ["deployment adapter", "billing", "template reviewers"],
    offers: ["ZIP ingestion", "site generation", "project profiles"],
    targetOutcome: "A creator can upload, publish, and share a project in one session.",
    creator: "Resonance Network",
    collaborators: 6,
    replications: 5,
    support: 810,
    resonance: 92,
  },
  {
    id: "node-neighborhood-skills",
    title: "Neighborhood Skill Exchange",
    summary: "A local opportunity node matching immediate project needs with people who can contribute a complementary skill nearby.",
    pathway: "hybrid",
    status: "forming",
    tags: ["need-in-proximity", "jobs", "community"],
    needs: ["local hosts", "privacy review", "opportunity seeders"],
    offers: ["micro-jobs", "mentorship", "real-world outcomes"],
    targetOutcome: "Ten useful matches that lead to completed paid or collaborative work.",
    creator: "Open Circle",
    collaborators: 9,
    replications: 1,
    support: 135,
    resonance: 81,
  },
];

export const starterMatches: PersonMatch[] = [
  {
    id: "match-1",
    name: "Mara",
    role: "Refiner",
    strength: "turning experimental ideas into rigorous, readable protocols",
    complement: "Your node needs method review before the next replication round.",
    sharedGoal: "make unconventional research testable without sanding off the original idea",
    zone: "Bay Area • remote friendly",
    resonance: 91,
    availableFor: ["protocol review", "experiment design", "documentation"],
  },
  {
    id: "match-2",
    name: "Devin",
    role: "Builder",
    strength: "shipping small full-stack products and deployment automation",
    complement: "Your launcher needs a reliable deployment adapter and billing boundary.",
    sharedGoal: "help independent creators launch without infrastructure becoming the product",
    zone: "Remote • 4h overlap",
    resonance: 87,
    availableFor: ["deployment", "GitOps", "platform engineering"],
  },
  {
    id: "match-3",
    name: "Imani",
    role: "Connector",
    strength: "community operations and turning loose interest into recurring participation",
    complement: "Your field project needs replicators and a clear invitation loop.",
    sharedGoal: "make collaboration useful enough that people return for the work, not the feed",
    zone: "Nearby zone available after opt-in",
    resonance: 84,
    availableFor: ["community pilots", "onboarding", "field projects"],
  },
];

export const starterMissions: Mission[] = [
  {
    id: "mission-1",
    title: "Publish the first complete node",
    objective: "Move one project from scattered materials to a public node with a test, ask, and next action.",
    pathway: "hybrid",
    status: "active",
    role: "Architect / Creator",
    whyNow: "It turns the network from a promise into an observable object other people can join, test, or support.",
    actions: [
      { id: "a1", label: "Choose the project and target outcome", done: true },
      { id: "a2", label: "Attach source files or repository", done: true },
      { id: "a3", label: "Define what another person can do next", done: false },
      { id: "a4", label: "Publish node and capture first response", done: false },
    ],
    evidence: ["source package attached", "project outcome drafted"],
    resonance: 86,
  },
  {
    id: "mission-2",
    title: "Recruit the missing role",
    objective: "Find one person whose strengths answer a live project need and give them a bounded, useful entry point.",
    pathway: "purpose",
    status: "queued",
    role: "Connector",
    whyNow: "The project is large enough that the next gain comes from complementarity, not another solo feature pass.",
    actions: [
      { id: "b1", label: "Name the missing capability", done: false },
      { id: "b2", label: "Review three high-context matches", done: false },
      { id: "b3", label: "Send one concrete collaboration invitation", done: false },
    ],
    evidence: [],
    resonance: 79,
  },
];

export const starterExperiments: Experiment[] = [
  {
    id: "exp-1",
    title: "Golden Crucible Replication 03",
    theory: "The proposed field condition should produce an observable pattern that can be logged consistently across independent participants.",
    variables: ["session duration", "participant state", "environment", "instrument readings"],
    method: "Use the shared protocol, log pre/post observations, attach raw instrument exports when available, and record protocol deviations.",
    observables: ["self-report delta", "sensor delta", "repeatability", "protocol adherence"],
    status: "running",
    replications: 2,
  },
  {
    id: "exp-2",
    title: "Need-in-Proximity Pilot",
    theory: "A context-aware opportunity prompt can increase useful local collaboration when users control visibility and opt in to reveal identity.",
    variables: ["distance band", "declared need", "availability", "match reason"],
    method: "Create opt-in opportunity zones, show generalized needs first, and record accepted, declined, completed, and blocked matches.",
    observables: ["acceptance rate", "completion rate", "time-to-match", "user comfort"],
    status: "draft",
    replications: 0,
  },
];

export const starterOffers: EnterpriseOffer[] = [
  {
    id: "offer-1",
    title: "Launch Package Review",
    type: "service",
    value: "$65 fixed",
    state: "open",
    description: "Review a creator node for clarity, deployment readiness, and a clean call-to-action before launch.",
  },
  {
    id: "offer-2",
    title: "Protocol Documentation Sprint",
    type: "job",
    value: "$180–$260",
    state: "open",
    description: "Convert experiment notes into a versioned protocol with variables, observables, and a replication checklist.",
  },
  {
    id: "offer-3",
    title: "Field Project Microgrant",
    type: "funding",
    value: "$500 pool",
    state: "open",
    description: "Small support pool for projects that publish a measurable target, transparent log, and replication or delivery plan.",
  },
];
